### ISSUE TITLE
Source map support?

### ISSUE THREAD

**Issue by cowboy** [gruntjs/grunt-contrib-stylus#118]
Looks like Stylus supports some kind of source maps now, per LearnBoost/stylus#1655.

Thoughts?

**Comment by AliMD** [comment]
excuse me but why this issue stopped ?!
can you please add this feature and release v0.21 ?
thank you in advance

**Comment by flying-sheep** [comment]
@AliMD it isn’t. if you refer to the [ !⃝  Closed] above your comment, and look closely, you’ll see that’s for issue #72, where this issue was mentioned in.

**Comment by AliMD** [comment]
dear @flying-sheep
sorry for interrupt and continue the discussion
I check bootstrap-stylus#72 again but i cant understand relation of that issue to this feature
anyway can you tell me when we can have it ?
thank you in advance

**Comment by flying-sheep** [comment]
i understand: you didn’t think that this issue is closed, but you were just complaining that there is no progress. sorry, i have no time ATM. why don’t you try fixing this yourself?

**Comment by icodeforlove** [comment]
@flying-sheep exorcist doesnt currently support css :/

the easy solution for me was to just have `postcss` generate the sourcemap for me.

**Comment by Enideo** [comment]
I just read the grunt task code for stylus (https://github.com/gruntjs/grunt-contrib-stylus/blob/master/tasks/stylus.js#L134).
Any unknown options are passed to stylus with the set method, so you can use the stylus js api as explained here:
https://learnboost.github.io/stylus/docs/sourcemaps.html#javascript-api
I used the following example config and got sourcemaps working for me straight away.
```
options:{
  sourcemap:{
    inline:true
  }
}
```

**Comment by argyleink** [comment]
@Enideo hahahaha amazing! Works like a charm. Thanks for making us look like dorks! =)

**Comment by pixeldrew** [comment]
Inline isn't the problem and has always worked. When you want to just point
to the real source you cannot do that because the paths are munged.

Drew Foehn <me@drewfoe.hn>
+1 (347) 443-4031

**Comment by zenopopovici** [comment]
@Enideo THANK YOU! :)

**Comment by dielok** [comment]
@Enideo  Thank you!

**Comment by dielok** [comment]
@Enideo  Thank you!
