### ISSUE TITLE
Warning: undefined is not a function

### ISSUE THREAD

**Issue by erickbelfy** [gruntjs/grunt-contrib-stylus#132]
have you guys already threw this error `Warning: undefined is not a function Use` i've configured an simple stylus file routine, take a look:

`module.exports = {
  production: {
      files: {
        'assets/build/styles/main.css': 'assets/styles/main.styl',
      }
    }
};
`

Could you guys help me with that? Thanks

**Comment by arthurvr** [comment]
Could you please post your whole Gruntfile, or at least the configuration you used for this task? Also, it would be handy to see your whole trace.

**Comment by vladikoff** [comment]
In addition 

> Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
