### ISSUE TITLE
does not compress normalize.css

### ISSUE THREAD

**Issue by erkanunluturk** [gruntjs/grunt-contrib-stylus#134]
gruntfile.js

```javascript
stylus: {
  compile: {
    options: {
       compress: true,
       'include css': true
    },
    files: {
       'public/css/main.css': 'resources/stylus/main.styl' // 1:1 compile
    }
  }
}
```
main.styl
```stylus
@import "./normalize.css"
```

#### does not work compression.

**Comment by vladikoff** [comment]
Not a grunt-contrib-stylus issue. 
Same output using `stylus --compress --include-css < main.styl > some.css`

**Comment by vladikoff** [comment]
I suggest filing a bug @ https://github.com/learnboost/stylus if you expect this behaviour
