### ISSUE TITLE
Can grunt compile the stylus file separately

### ISSUE THREAD

**Issue by yushengh** [gruntjs/grunt-contrib-stylus#137]
When grunt run compiling a stylus directory. It will run similar like <code>stylus directory/</code>
Can grunt run like <code>stylus file1.styl, stylus file2.styl, stylus file3.styl</code> separately and each of the compiling are parallel so that each of them will not influence each other? 

```
directory/ 
    file1.styl
    file2.styl
    file3.styl
```

**Comment by shama** [comment]
Please use `expand: true`. See this section in the Grunt docs: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically
