### ISSUE TITLE
How to use grunt stylus to compile each file to the original folder?

### ISSUE THREAD

**Issue by qiuzuhui** [gruntjs/grunt-contrib-stylus#142]
what i want to do is compile stylus files to the same folder where the stylus file in . like

`files: { 'src/**/*.css':'src/**/*.styl']`

Even I have try the same config on the documnet
`
options: {
  relativeDest: 'out'
},
files: [{
  src: ['src/components/*/*.styl'],
  ext: '.css'
}]
`
and failed.
what's the correct ?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
