### ISSUE TITLE
Bump to stylus 0.53 is needed!

### ISSUE THREAD

**Issue by Alxblsk** [gruntjs/grunt-contrib-stylus#143]
I see that Stylus was updated to 0.53 and contains lots of interesting enhancements: https://github.com/stylus/stylus/blob/dev/History.md#0530--2015-12-14

Could you update grunt-contrib-stylus according with latest changes?

Thank you in advance.

**Comment by sapegin** [comment]
Can you send a PR?

**Comment by Alxblsk** [comment]
@sapegin Please check it out.
