### ISSUE TITLE
Allow empty stylus folders

### ISSUE THREAD

**Issue by martinheidegger** [gruntjs/grunt-contrib-stylus#55]
I am trying to create a grunt template that can be used in different projects and I would like to define a stylus definition for files that are optional to exist or without content. It would be cool if stylus would continue executing if it has nothing to do. Right now it stops with following error: 

```
>> Destination not written because compiled files were empty.
```

To me it is okay if this there needs to be a flag like "ignoreEmpty".

**Comment by arthurvr** [comment]
> sounds like #52 could fix this too

I guess this issue can be closed?
