### ISSUE TITLE
failed to locate @import file nib.styl

### ISSUE THREAD

**Issue by PixelVibe** [gruntjs/grunt-contrib-stylus#90]
Hello

I am having the same issue as #2 

Running "stylus:compile" (stylus) task
Error: src/assets/styles/reset.styl:1
1| @import 'nib'
failed to locate @import file nib.styl

I am using version 0.13.0 and my gruntfile.js code for stylus is

```
stylus: {compile: {files: {css_files_bin: css_files_src} } },

    watch: {
        stylus:{
          files: 'src/assets/styles/*.styl',
          tasks: 'stylus'
        },
        livereload: {
            options: { livereload: true },
            files: [bin_styles + '*.css', bin_scripts + '*.js', 'static/*.html', '*.php', 'templates/*.php', bin_images + '**/*.*']
        }
    },
```

Am I missing something or didn't configure it properly?

**Comment by arthurvr** [comment]
> I am using version 0.13.0 and my gruntfile.js code for stylus is

Are you also having this issue with the latest version? Just so we know if the issue still exists or if it's fixed already.

**Comment by PixelVibe** [comment]
Well, since then I switched to gulp, so I cant really help you on that.

**Comment by blackdynamo** [comment]
@arthurvr Since @PixelVibe has switched to grunt, I can probably answer your question.

I am not seeing this issue in 0.21.0. which as of the time of this post is the latest. The task seems to be working as expected.
